# Generated by Django 3.2.8 on 2022-01-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220104_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
