# Generated by Django 3.2.8 on 2022-01-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hasReminded',
            field=models.BooleanField(default=False),
        ),
    ]
